### ISSUE TITLE
Plans to update to go/types?

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-importer#5]
This package currently works with the old import path at "golang.org/x/tools/go/types". Plans to update it to the new "go/types"?

The interface will need to change slightly. See https://github.com/gopherjs/gopherjs/commit/a240d35ae72a9f92e4115ce0bd8efb288caf26b1 for example.

The method signature:

```Go
Import(imports map[string]*types.Package, path string) (pkg *types.Package, err error)
```

Will need to become:

```Go
Import(path string) (pkg *types.Package, err error)
```

In order to satisfy [`types.Importer`](https://godoc.org/go/types#Importer).

**Comment by dominikh** [comment]
Is this package even of use anymore? I originally wrote it for errcheck, because at the time go/types didn't offer a similar loader. Now errcheck uses x/tools/go/loader, so I have to suspect that my package isn't required anymore?

**Comment by dominikh** [comment]
go/loader seems to only look at source files, not .a files – so this package is still different. However, as far as I am aware, a loader similar to mine is planned? I would really prefer to let this package die.

**Comment by shurcooL** [comment]
I see.

I use it, but not actively. I'd be happy if an equivalent functionality can be achieved using standard library in the future. My need is not critical, so you're welcome to deprecate this library if you wish.

**Comment by shurcooL** [comment]
See https://godoc.org/honnef.co/go/importer?importers.

**Comment by shurcooL** [comment]
> I would really prefer to let this package die.

In that case, I'll close this feature request since I don't need it critically.

**Comment by shurcooL** [comment]
This package is now failing to compile because it imports Go packages that have been deprecated and removed.

Can you let me know what you're planning to do, to deprecate this package or update it so that it builds?

I'll reiterate what I said before:

> I'd be happy if an equivalent functionality can be achieved using standard library in the future. My need is not critical, so you're welcome to deprecate this library if you wish.

However, I need to know which of the two it'll be. The reason is so I can decide what to do about my project which is currently failing to build, whether I should rewrite it to avoid this package, or wait for you to fix it. Thanks!

**Comment by shurcooL** [comment]
FWIW, I went ahead and stopped using this package in favor of `go/importer` from std lib.

It works on pure Go packages, but not Cgo ones. See https://github.com/shurcooL/Conception-go/commit/98ba0ba3f57cfb1f307fd88c1abefa0d0694ad45 for details.

Would you consider reducing the scope of this package to simply wrap `go/importer` from standard library and continue to offer a `GcFallback` option?

**Comment by dominikh** [comment]
I'll remove this package. It's never been a good loader to use. While it did support cgo, it did so in a way that could lead to inconsistent results, because we used gc object files that might've been older than the source. Additionally, it doesn't support vendoring.

A better way to support cgo right now is to use `/x/tools/go/loader`. It parses all packages from source, and does support cgo (it does invoke C compilers, just like `go build` does.)

**Comment by shurcooL** [comment]
I didn't know that, that's great, thanks.
